### ISSUE TITLE
Android Project build tip "6 files found with path 'META-INF/LICENSE.md'"

### ISSUE THREAD

**Issue by RavenLiao** [ChromasIV/KTweet#11]
**Describe the bug**
implementation("com.chromasgaming:ktweet:1.3.0") in build.gradle, then build App, it happen error：
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
> 6 files found with path 'META-INF/LICENSE.md' from inputs:”
> ...\.gradle\caches\modules>2\files>2.1\org.junit.jupiter\junit>jupiter>params\5.9.0\d6b6ccd3585351f617b06f066675271afebe9b28\junit>jupiter>params>5.9.0.jar
> ...\.gradle\caches\modules>2\files>2.1\org.junit.jupiter\junit>jupiter>engine\5.9.0\cc1cb5efae97493dcffb687253a0964ad2e7b99\junit>jupiter>engine>5.9.0.jar
> ...\.gradle\caches\modules>2\files>2.1\org.junit.jupiter\junit>jupiter>api\5.9.0\a44f7eba3ea214f6ec87ad9fccd3b2ac4681a4\junit>jupiter>api>5.9.0.jar
> ...\.gradle\caches\modules>2\files>2.1\org.junit.platform\junit>platform>engine\1.9.0\bd46891f01817b5ffdd368cb0482a34746610acb\junit>platform>engine>1.9.0.jar
> ...\.gradle\caches\modules>2\files>2.1\org.junit.platform\junit>platform>commons\1.9.0\b727889107fc28c7460b21d1083212f8ce7602c6\junit>platform>commons>1.9.0.jar
> ...\.gradle\caches\modules>2\files>2.1\org.junit.jupiter\junit>jupiter\5.9.0\db1cd1cd9e3138cf9e5ecb12a2ccc9cfbdf6a1d\junit>jupiter>5.9.0.jar

**Will even happen this error in hello world project.**

**To Reproduce**
1. new Android Project in AndroidStudio
2. add implementation("com.chromasgaming:ktweet:1.3.0") in build.gradle
3. build app

**Expected behavior**
build should success 

**Additional context**
add this in app build.gradle will fix, but it is not a good solve.
```
android {
   ...

    packagingOptions {
        resources.excludes += "META-INF/LICENSE.md"
        resources.excludes += "META-INF/LICENSE-notice.md"
    }
}
```

**Comment by ChromasIV** [comment]
Looking into it, thanks for the report!

**Comment by ChromasIV** [comment]
I haven't forgotten. I've been slammed with other things. Will be looking into this week!

**Comment by ChromasIV** [comment]
After researching it some, the issue lies with Gradle and Android not liking duplicate files. I will exclude the LICENSE going forward. Going to look into how I can test this down the road for validation. Expect an update sometime this week that will exclude the license.

**Comment by ChromasIV** [comment]
excluding in new version, currently in development.
